name: Release

on:
  push:
    tags:
      - 'v*' # Triggers on tags like v1.0.0

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Extension
        run: npm run package

      - name: Package VSIX
        run: npx @vscode/vsce package --no-dependencies
        id: vsix

      - name: Publish to VS Code Marketplace
        run: npx @vscode/vsce publish --no-dependencies -p ${{ secrets.VSCE_PAT }}
        continue-on-error: true

      - name: Publish to Open VSX Registry
        run: npx ovsx publish *.vsix -p ${{ secrets.OVSX_PAT }}
        continue-on-error: true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          files: "*.vsix"
          generate_release_notes: true
